name: Laravel Tests
on:
push:
branches: [ "main" ]
pull_request:
branches: [ "main" ]
jobs:
laravel-tests:
runs-on: ubuntu-latest
steps:
# 1. Checkout source code
- name: Checkout repository
uses: actions/checkout@v4
# 2. Setup PHP
- name: Setup PHP
uses: shivammathur/setup-php@v2
with:
php-version: '8.2'
extensions: mbstring, bcmath
coverage: none
# 3. Cache dependencies
- name: Get composer cache directory
id: composer-cache
run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
- name: Cache Composer dependencies
uses: actions/cache@v3
with:
path: ${{ steps.composer-cache.outputs.dir }}
key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
restore-keys: ${{ runner.os }}-composer-
# 4. Install dependencies
- name: Install dependencies
run: composer install --no-progress --prefer-dist --optimize-autoloader
# 5. Copy environment file
- name: Create .env file
run: |
cp .env.example .env
php artisan key:generate
# 6. Run tests
- name: Run PHPUnit tests
run: php artisan test
